package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.34

import (
	"context"
	"errors"
	"fmt"
	"strconv"
	"strings"
	"time"

	"github.com/KnightHacks/knighthacks_hackathon/graph/generated"
	"github.com/KnightHacks/knighthacks_hackathon/graph/model"
	"github.com/KnightHacks/knighthacks_shared/auth"
	"github.com/KnightHacks/knighthacks_shared/models"
	"github.com/KnightHacks/knighthacks_shared/pagination"
)

// Hackathon is the resolver for the hackathon field.
func (r *eventResolver) Hackathon(ctx context.Context, obj *model.Event) (*model.Hackathon, error) {
	return r.Repository.GetHackathonByEvent(ctx, obj)
}

// Sponsors is the resolver for the sponsors field.
func (r *hackathonResolver) Sponsors(ctx context.Context, obj *model.Hackathon, first int, after *string) (*model.SponsorsConnection, error) {
	a, err := pagination.DecodeCursor(after)
	if err != nil {
		return nil, err
	}
	sponsors, total, err := r.Repository.GetHackathonSponsors(ctx, obj, first, a)
	if err != nil {
		return nil, err
	}
	connection := model.SponsorsConnection{Sponsors: sponsors,
		TotalCount: total,
		PageInfo:   pagination.GetPageInfo(sponsors),
	}
	return &connection, err
}

// Events is the resolver for the events field.
func (r *hackathonResolver) Events(ctx context.Context, obj *model.Hackathon, first int, after *string) (*model.EventsConnection, error) {
	a, err := pagination.DecodeCursor(after)
	if err != nil {
		return nil, err
	}
	events, total, err := r.Repository.GetHackathonEvents(ctx, obj, first, a)
	if err != nil {
		return nil, err
	}
	connection := model.EventsConnection{Events: events,
		TotalCount: total,
		PageInfo:   pagination.GetPageInfo(events),
	}
	return &connection, err
}

// Status is the resolver for the status field.
func (r *hackathonResolver) Status(ctx context.Context, obj *model.Hackathon) (model.HackathonStatus, error) {
	now := time.Now().UTC()

	if obj.StartDate.After(now) {
		return model.HackathonStatusFuture, nil
	}
	if obj.EndDate.Before(now) {
		return model.HackathonStatusPast, nil
	}

	return model.HackathonStatusPresent, nil
}

// Applications is the resolver for the applications field.
func (r *hackathonResolver) Applications(ctx context.Context, obj *model.Hackathon, first int, after *string, status model.ApplicationStatus) (*model.HackathonApplicationConnection, error) {
	hackathons, total, err := r.Repository.GetApplicationsByHackathon(ctx, obj, first, after, status)

	connection := model.HackathonApplicationConnection{Applications: hackathons,
		TotalCount: total,
		PageInfo:   pagination.GetPageInfo(hackathons),
	}
	return &connection, err
}

// Hackathon is the resolver for the hackathon field.
func (r *hackathonApplicationResolver) Hackathon(ctx context.Context, obj *model.HackathonApplication) (*model.Hackathon, error) {
	hackathonIdInt, err := strconv.Atoi(strings.Split(obj.ID, "-")[0])
	if err != nil {
		return nil, err
	}

	return r.Repository.GetHackathon(ctx, hackathonIdInt)
}

// CreateHackathon is the resolver for the createHackathon field.
func (r *mutationResolver) CreateHackathon(ctx context.Context, input model.HackathonCreateInput) (*model.Hackathon, error) {
	return r.Repository.CreateHackathon(ctx, &input)
}

// UpdateHackathon is the resolver for the updateHackathon field.
func (r *mutationResolver) UpdateHackathon(ctx context.Context, id string, input model.HackathonUpdateInput) (*model.Hackathon, error) {
	hackathonIdInt, err := strconv.Atoi(id)
	if err != nil {
		return nil, err
	}

	return r.Repository.UpdateHackathon(ctx, hackathonIdInt, &input)
}

// DeleteHackathon is the resolver for the deleteHackathon field.
func (r *mutationResolver) DeleteHackathon(ctx context.Context, id string) (bool, error) {
	hackathonIdInt, err := strconv.Atoi(id)
	if err != nil {
		return false, err
	}

	return r.Repository.DeleteHackathon(ctx, hackathonIdInt)
}

// AcceptApplicant is the resolver for the acceptApplicant field.
func (r *mutationResolver) AcceptApplicant(ctx context.Context, hackathonID string, userID string) (bool, error) {
	hackathonIdInt, err := strconv.Atoi(hackathonID)
	if err != nil {
		return false, err
	}
	userIdInt, err := strconv.Atoi(userID)
	if err != nil {
		return false, err
	}

	return r.Repository.AcceptApplicant(ctx, hackathonIdInt, userIdInt)
}

// DenyApplicant is the resolver for the denyApplicant field.
func (r *mutationResolver) DenyApplicant(ctx context.Context, hackathonID string, userID string) (bool, error) {
	hackathonIdInt, err := strconv.Atoi(hackathonID)
	if err != nil {
		return false, err
	}
	userIdInt, err := strconv.Atoi(userID)
	if err != nil {
		return false, err
	}

	return r.Repository.DenyApplicant(ctx, hackathonIdInt, userIdInt)
}

// UpdateApplication is the resolver for the updateApplication field.
func (r *mutationResolver) UpdateApplication(ctx context.Context, hackathonID string, userID string, input model.HackathonApplicationInput) (*model.HackathonApplication, error) {
	claims, ok := ctx.Value("AuthorizationUserClaims").(*auth.UserClaims)
	if !ok {
		return nil, errors.New("unable to retrieve user claims, most likely forgot to set @hasRole directive")
	}
	if claims.Role != models.RoleAdmin && claims.UserID != userID {
		return nil, errors.New("unauthorized to update hackathon application that is not you")
	}

	hackathonIdInt, err := strconv.Atoi(hackathonID)
	if err != nil {
		return nil, err
	}

	_, err = r.Repository.GetHackathon(ctx, hackathonIdInt)
	if err != nil {
		return nil, err
	}

	var application *model.HackathonApplication

	userIdInt, err := strconv.Atoi(hackathonID)
	if err != nil {
		return nil, err
	}

	application, err = r.Repository.UpdateApplication(ctx, hackathonIdInt, userIdInt, input)
	if err != nil {
		return nil, err
	}
	application.UserID = userID
	application.HackathonID = hackathonID
	return application, err
}

// ApplyToHackathon is the resolver for the applyToHackathon field.
func (r *mutationResolver) ApplyToHackathon(ctx context.Context, hackathonID string, input model.HackathonApplicationInput) (string, error) {
	claims, ok := ctx.Value("AuthorizationUserClaims").(*auth.UserClaims)
	if !ok {
		return "", errors.New("unable to retrieve user claims, most likely forgot to set @hasRole directive")
	}

	hackathonIdInt, err := strconv.Atoi(hackathonID)
	if err != nil {
		return "", err
	}

	userIdInt, err := strconv.Atoi(claims.UserID)
	if err != nil {
		return "", err
	}

	err = r.Repository.ApplyToHackathon(ctx, hackathonIdInt, userIdInt, input)
	if err != nil {
		return "", err
	}

	url, err := r.AzureBlobClient.CreatePreSignedURL(hackathonID, claims.UserID)
	if err != nil {
		return "", err
	}
	return url, nil
}

// CurrentHackathon is the resolver for the currentHackathon field.
func (r *queryResolver) CurrentHackathon(ctx context.Context) (*model.Hackathon, error) {
	return r.Repository.GetCurrentHackathon(ctx)
}

// Hackathons is the resolver for the hackathons field.
func (r *queryResolver) Hackathons(ctx context.Context, filter model.HackathonFilter) ([]*model.Hackathon, error) {
	return r.Repository.GetHackathons(ctx, &filter)
}

// GetHackathon is the resolver for the getHackathon field.
func (r *queryResolver) GetHackathon(ctx context.Context, id string) (*model.Hackathon, error) {
	hackathonIdInt, err := strconv.Atoi(id)
	if err != nil {
		return nil, err
	}

	return r.Repository.GetHackathon(ctx, hackathonIdInt)
}

// GetApplication is the resolver for the getApplication field.
func (r *queryResolver) GetApplication(ctx context.Context, hackathonID string, userID string) (*model.HackathonApplication, error) {
	claims, ok := ctx.Value("AuthorizationUserClaims").(*auth.UserClaims)
	if !ok {
		return nil, errors.New("unable to retrieve user claims, most likely forgot to set @hasRole directive")
	}
	if claims.Role != models.RoleAdmin && claims.UserID != userID {
		return nil, errors.New("unauthorized to update hackathon application that is not you")
	}

	return r.Entity().FindHackathonApplicationByID(ctx, fmt.Sprintf("%s-%s", hackathonID, userID))
}

// Hackathons is the resolver for the hackathons field.
func (r *sponsorResolver) Hackathons(ctx context.Context, obj *model.Sponsor) ([]*model.Hackathon, error) {
	return r.Repository.GetHackathonsBySponsor(ctx, obj)
}

// Applications is the resolver for the applications field.
func (r *userResolver) Applications(ctx context.Context, obj *model.User) ([]*model.HackathonApplication, error) {
	return r.Repository.GetApplicationsByUser(ctx, obj)
}

// Event returns generated.EventResolver implementation.
func (r *Resolver) Event() generated.EventResolver { return &eventResolver{r} }

// Hackathon returns generated.HackathonResolver implementation.
func (r *Resolver) Hackathon() generated.HackathonResolver { return &hackathonResolver{r} }

// HackathonApplication returns generated.HackathonApplicationResolver implementation.
func (r *Resolver) HackathonApplication() generated.HackathonApplicationResolver {
	return &hackathonApplicationResolver{r}
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// Sponsor returns generated.SponsorResolver implementation.
func (r *Resolver) Sponsor() generated.SponsorResolver { return &sponsorResolver{r} }

// User returns generated.UserResolver implementation.
func (r *Resolver) User() generated.UserResolver { return &userResolver{r} }

type eventResolver struct{ *Resolver }
type hackathonResolver struct{ *Resolver }
type hackathonApplicationResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type sponsorResolver struct{ *Resolver }
type userResolver struct{ *Resolver }
