// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"fmt"
	"io"
	"strconv"
	"time"

	"github.com/99designs/gqlgen/graphql"
	"github.com/KnightHacks/knighthacks_shared/models"
)

type Connection interface {
	IsConnection()
}

type Event struct {
	ID        string     `json:"id"`
	Hackathon *Hackathon `json:"hackathon"`
}

func (Event) IsEntity() {}

type EventsConnection struct {
	TotalCount int              `json:"totalCount"`
	PageInfo   *models.PageInfo `json:"pageInfo"`
	Events     []*Event         `json:"events"`
}

func (EventsConnection) IsConnection() {}

type Hackathon struct {
	ID         string              `json:"id"`
	Term       *Term               `json:"term"`
	StartDate  time.Time           `json:"startDate"`
	EndDate    time.Time           `json:"endDate"`
	Applicants *UsersConnection    `json:"applicants"`
	Attendees  *UsersConnection    `json:"attendees"`
	Sponsors   *SponsorsConnection `json:"sponsors"`
	Events     *EventsConnection   `json:"events"`
	Status     HackathonStatus     `json:"status"`
	Pending    bool                `json:"pending"`
	Attending  bool                `json:"attending"`
}

func (Hackathon) IsEntity() {}

type HackathonApplicationInput struct {
	WhyAttend             []string        `json:"whyAttend"`
	WhatDoYouWantToLearn  []string        `json:"whatDoYouWantToLearn"`
	ShareInfoWithSponsors bool            `json:"shareInfoWithSponsors"`
	Resume                *graphql.Upload `json:"resume"`
}

type HackathonCreateInput struct {
	Year      int       `json:"year"`
	Semester  Semester  `json:"semester"`
	Sponsors  []string  `json:"sponsors"`
	Events    []string  `json:"events"`
	StartDate time.Time `json:"startDate"`
	EndDate   time.Time `json:"endDate"`
}

type HackathonFilter struct {
	Year     int       `json:"year"`
	Semester *Semester `json:"semester"`
}

type HackathonUpdateInput struct {
	Year                *int      `json:"year"`
	Semester            *Semester `json:"semester"`
	AddedSponsors       []string  `json:"addedSponsors"`
	RemovedSponsors     []string  `json:"removedSponsors"`
	AddedEvents         []string  `json:"addedEvents"`
	RemovedEvents       []string  `json:"removedEvents"`
	AddedParticipants   []string  `json:"addedParticipants"`
	RemovedParticipants []string  `json:"removedParticipants"`
}

type Sponsor struct {
	ID         string       `json:"id"`
	Hackathons []*Hackathon `json:"hackathons"`
}

func (Sponsor) IsEntity() {}

type SponsorsConnection struct {
	TotalCount int              `json:"totalCount"`
	PageInfo   *models.PageInfo `json:"pageInfo"`
	Sponsors   []*Sponsor       `json:"sponsors"`
}

func (SponsorsConnection) IsConnection() {}

type Term struct {
	Year     int      `json:"year"`
	Semester Semester `json:"semester"`
}

type User struct {
	ID                 string       `json:"id"`
	AttendedHackathons []*Hackathon `json:"attendedHackathons"`
	AppliedHackathons  []*Hackathon `json:"appliedHackathons"`
}

func (User) IsEntity() {}

type UsersConnection struct {
	TotalCount int              `json:"totalCount"`
	PageInfo   *models.PageInfo `json:"pageInfo"`
	Users      []*User          `json:"users"`
}

func (UsersConnection) IsConnection() {}

type HackathonStatus string

const (
	HackathonStatusPast    HackathonStatus = "PAST"
	HackathonStatusPresent HackathonStatus = "PRESENT"
	HackathonStatusFuture  HackathonStatus = "FUTURE"
)

var AllHackathonStatus = []HackathonStatus{
	HackathonStatusPast,
	HackathonStatusPresent,
	HackathonStatusFuture,
}

func (e HackathonStatus) IsValid() bool {
	switch e {
	case HackathonStatusPast, HackathonStatusPresent, HackathonStatusFuture:
		return true
	}
	return false
}

func (e HackathonStatus) String() string {
	return string(e)
}

func (e *HackathonStatus) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = HackathonStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid HackathonStatus", str)
	}
	return nil
}

func (e HackathonStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type Semester string

const (
	SemesterFall   Semester = "FALL"
	SemesterSpring Semester = "SPRING"
	SemesterSummer Semester = "SUMMER"
)

var AllSemester = []Semester{
	SemesterFall,
	SemesterSpring,
	SemesterSummer,
}

func (e Semester) IsValid() bool {
	switch e {
	case SemesterFall, SemesterSpring, SemesterSummer:
		return true
	}
	return false
}

func (e Semester) String() string {
	return string(e)
}

func (e *Semester) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Semester(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Semester", str)
	}
	return nil
}

func (e Semester) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
